# Basic
title: Ann的小屋
subtitle: 凡事当做则作，若一味因循，大误终身
welcome_message: <a href="https://github.com/AnXiaoye1/AnXiaoye1.github.io" target="_blank">欢迎来到 Ann的小屋！</a>
description: 接下来，与你同行
creator: <a href="http://www.anxiaoye.xyz">@AnXiaoye</a>

url: "https://www.anxiaoye.xyz/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: orange

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 进入博客

# Navigation buttons in the front page.
nav:
    - {title: 关于, description: 关于作者, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 北梦木南思伊
    github: AnXiaoye1
    twitter: 
    gplus: 
    mail: zhuye95911@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
